[package]
name = "malus"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.30.2", default-features = false, features = ["layout-cache", "std"] }
ratcn = { version = "0.0.3", features = ["termina"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "process", "io-util"] }
tokio-tungstenite = "0.26"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "6.0"
libc = "0.2"
url = "2.5"
zbus = { version = "5", default-features = false, features = ["tokio"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
unicode-width = "0.2"
toml = "1.1.5"
