[workspace]
resolver = "2"
members = [
    "crates/malus-core",
    "crates/malus-protocol",
    "crates/malus-client",
    "crates/malus-daemon",
    "crates/malus-apple",
    "crates/malus-web-runtime",
    "crates/malus-cli",
    "apps/malus-gui",
    "apps/malus-gui-next",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Malus Contributors"]
repository = "https://github.com/sea-deep/malus"
