[package]
name = "malus-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "malus"
path = "src/main.rs"

[dependencies]
malus-client = { path = "../malus-client" }
malus-protocol = { path = "../malus-protocol" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "net", "io-util"] }
thiserror = "2"
serde_json = "1.0"

